# Visits https://github.com/anmol098/waka-readme-stats for details.
name: Waka Readme

on:
  schedule:
    # Runs at 12.30am in UTC+8
    - cron: "30 16 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with 数据统计
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
         WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "True"
          SECTION_NAME: "数据统计"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_PROFILE_VIEWS: "False"
          UPDATED_DATE_FORMAT: "%Y/%m/%d %H:%M:%S"
